#!/usr/bin/env bash

function pack {
	# Specifically for this package
	find	postproc-$1/$(ls postproc-$1 | tail -n1) \
		-name '*+netcal.uvfits' \
		-type f | grep -v '\/\.' > $1-netcal.in

	# Sort and make the list unique
	sort $1-netcal.in      |\
		uniq           |\
		grep -v 'SGRA' |\
		grep -v step    \
		> $1-netcal.ls && rm $1-netcal.in

	# Actually taring
	tar	--transform 's/^hops-/er5-hops-/g' \
		-czhf ../er5-$1-netcal.tgz \
		--files-from=$1-netcal.ls
}

pack aips-hi
pack aips-lo

pack casa-hi
pack casa-lo

pack hops-hi
pack hops-lo
