#!/usr/bin/env bash

function pack_aips {
	# Specifically for this package
	find	aips-$1 \
		-type f -name '*.uvfits' > aips-$1-uvfits.in

	# Sort and make the list unique
	sort aips-$1-uvfits.in | uniq > aips-$1-uvfits.ls && rm aips-$1-uvfits.in
	
	# Actually taring
	tar	--transform 's|^aips-|er5-aips-|g' \
		-czhf ../er5-aips-$1-uvfits.tgz \
		--files-from=aips-$1-uvfits.ls
}

function pack_casa {
	# Specifically for this package
	find	casa-$1 \
		-type f -name '*.uvfits' > casa-$1-uvfits.in

	# Sort and make the list unique
	sort casa-$1-uvfits.in | uniq > casa-$1-uvfits.ls && rm casa-$1-uvfits.in
	
	# Actually taring
	tar	--transform 's|^casa-|er5-casa-|g' \
		-czhf ../er5-casa-$1-uvfits.tgz \
		--files-from=casa-$1-uvfits.ls
}

function pack_hops {
	# Specifically for this package
	find	hops-$1/6.uvfits \
		-type f | grep -v '\/\.' > hops-$1-uvfits.in

	# Sort and make the list unique
	sort hops-$1-uvfits.in | uniq > hops-$1-uvfits.ls && rm hops-$1-uvfits.in

	# Actually taring
	tar	--transform 's|^hops-\(..\)/6.uvfits|er5-hops-\1|g' \
		-czhf ../er5-hops-$1-uvfits.tgz \
		--files-from=hops-$1-uvfits.ls
}

pack_aips hi
pack_aips lo

pack_casa hi
pack_casa lo

pack_hops hi
pack_hops lo
