#!/usr/bin/env bash

function pack {
	# For reputability, these are things that we should always include
	find	er1-hops-$1/*/bin \
		er1-hops-$1/*/log \
		er1-hops-$1/*/cf* \
		er1-hops-$1/*/data/adhoc \
		-type f > er1-hops-$1-uvfits.in

	# Specifically for this package
	find	er1-hops-$1/6.uvfits \
		-type f >> er1-hops-$1-uvfits.in

	# Sort and make the list unique
	sort er1-hops-$1-uvfits.in | uniq > er1-hops-$1-uvfits.ls && rm er1-hops-$1-uvfits.in

	# Actually taring
	tar -czhf er1-hops-$1-uvfits.tgz --files-from=er1-hops-$1-uvfits.ls
}

pack hi
pack lo
