#!/usr/bin/env bash

function pack {
	# Specifically for this package
	find	postproc-$1/$(ls postproc-$1 | tail -n2 | head -n1) \
		-type f | grep -v '\/\.' > $1-apriori.in

	# Sort and make the list unique
	sort $1-apriori.in    |\
		uniq          |\
		grep -v 'SGRA' \
		> $1-apriori.ls && rm $1-apriori.in

	# Actually taring
	tar	--transform 's/^hops-/er6-hops-/g' \
		-czhf ../er6-$1-apriori.tgz \
		--files-from=$1-apriori.ls
}

pack casa-hi
pack casa-lo

pack hops-hi
pack hops-lo
